### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by thorstenkampe** [kcsaff/getkey#1]
```
> python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import getkey
>>> getkey.getkey()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\PortableApps\Python\lib\site-packages\getkey\platforms.py", line 40, in getkey
    buffer += c
TypeError: must be str, not bytes
```

**Comment by bllngr** [comment]
I'm facing the same issue. Any update on this?

**Comment by li-rupert** [comment]
This pull request:
#4
solves this problem I believe.
