### ISSUE TITLE
CANT INSTALL!!!!

### ISSUE THREAD

**Issue by shadow00dev** [kcsaff/getkey#14]
ERROR: ```    ERROR: Command errored out with exit status 1:
     command: 'c:\users\mark7\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mark7\\AppData\\Local\\Temp\\pip-install-y5yz3fjh\\getkey\\setup.py'"'"'; __file__='"'"'C:\\Users\\mark7\\AppData\\Local\\Temp\\pip-install-y5yz3fjh\\getkey\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mark7\AppData\Local\Temp\pip-pip-egg-info-29ojwb12'
         cwd: C:\Users\mark7\AppData\Local\Temp\pip-install-y5yz3fjh\getkey\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mark7\AppData\Local\Temp\pip-install-y5yz3fjh\getkey\setup.py", line 37, in <module>
        long_description=read_description(),
      File "C:\Users\mark7\AppData\Local\Temp\pip-install-y5yz3fjh\getkey\setup.py", line 11, in read_description
        return fd.read()
      File "c:\users\mark7\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 876: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by joshvtech** [comment]
This package is no longer maintained - it seems.
Check [this comment](https://github.com/kcsaff/getkey/issues/2#issuecomment-611278429) for a fix.
