### ISSUE TITLE
[bug]: trouble installing getkey

### ISSUE THREAD

**Issue by iop3** [kcsaff/getkey#21]
After I enter `pip install getkey`, it returns the following error:

```
Collecting getkey
  Using cached getkey-0.6.5.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\aaron\AppData\Local\Temp\pip-install-p1wko10r\getkey_65db5911d39c456cb3e7fe07fbcc605c\setup.py", line 37, in <module>
          long_description=read_description(),
        File "C:\Users\aaron\AppData\Local\Temp\pip-install-p1wko10r\getkey_65db5911d39c456cb3e7fe07fbcc605c\setup.py", line 11, in read_description
          return fd.read()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 876: character maps to <undefined>
      [end of output]
```

Maybe some time can be spared for the bug to be fixed 😄

**Comment by iop3** [comment]
I see there is already a fix. Nevermind.
