### ISSUE TITLE
Installing Error: UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 876: character maps to <undefined>

### ISSUE THREAD

**Issue by BaseMax** [kcsaff/getkey#22]
```
Microsoft Windows [Version 10.0.22000.1098]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Max>pip install getkey
Collecting getkey
  Downloading getkey-0.6.5.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Max\AppData\Local\Temp\pip-install-anlunwwx\getkey_fc49247753c54fa9a34fc77cf4f4a9d3\setup.py", line 37, in <module>
          long_description=read_description(),
        File "C:\Users\Max\AppData\Local\Temp\pip-install-anlunwwx\getkey_fc49247753c54fa9a34fc77cf4f4a9d3\setup.py", line 11, in read_description
          return fd.read()
        File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 876: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\Max>pip install getkey
Collecting getkey
  Using cached getkey-0.6.5.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Max\AppData\Local\Temp\pip-install-p6mi5z9k\getkey_6404c92d3cd2405c851ac2445dbdf64b\setup.py", line 37, in <module>
          long_description=read_description(),
        File "C:\Users\Max\AppData\Local\Temp\pip-install-p6mi5z9k\getkey_6404c92d3cd2405c851ac2445dbdf64b\setup.py", line 11, in read_description
          return fd.read()
        File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 876: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by BaseMax** [comment]
```
C:\Users\Max>pip --version
pip 22.3 from C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
```

```
C:\Users\Max>python --version
Python 3.10.8
```

**Comment by h4rldev** [comment]
Have the same issue, don't know the cause

**Comment by jlemback** [comment]
I have the same issue, what to do??

**Comment by jlemback** [comment]
Error message:

C:\Users\jenni>pip install getkey
Collecting getkey
  Using cached getkey-0.6.5.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jenni\AppData\Local\Temp\pip-install-p9mfhp1q\getkey_6ed7fb4b1ab34df49be65936692a82df\setup.py", line 37, in <module>
          long_description=read_description(),
                           ^^^^^^^^^^^^^^^^^^
        File "C:\Users\jenni\AppData\Local\Temp\pip-install-p9mfhp1q\getkey_6ed7fb4b1ab34df49be65936692a82df\setup.py", line 11, in read_description
          return fd.read()
                 ^^^^^^^^^
        File "C:\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 876: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\jenni>

**Comment by greger555** [comment]
I also get thes issue:

C:\Users\Gregw>pip install getkey
Collecting getkey
  Using cached getkey-0.6.5.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Gregw\AppData\Local\Temp\pip-install-a1k37d3y\getkey_5dedb9269e7d431ea4084ba0440d716e\setup.py", line 37, in <module>
          long_description=read_description(),
                           ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Gregw\AppData\Local\Temp\pip-install-a1k37d3y\getkey_5dedb9269e7d431ea4084ba0440d716e\setup.py", line 11, in read_description
          return fd.read()
                 ^^^^^^^^^
        File "C:\Users\Gregw\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 876: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by h4rldev** [comment]
A fix is just installing getkey from the repo, (i think).

**Comment by greger555** [comment]
this is what helped me: 

in getkey, in the setup.py file change the code on line 9 from: 

`
def read_description():
    with open('README.rst') as fd:
        return fd.read()
`

to:

`def read_description():
    with open('README.rst') as fd:
        return fd.read(encoding="utf-8")`


wich forces the UTF-8 usage, and is apparently what we need


however this means you have to download getkey manually. Another issue with this is if you try to install getkey again after done this step, it will still error because pip automatically attempts to find the most updated version on pypi and ignores your directory. 

To solve this you need to use "pip install -e ." command instead of the infamous "pip install getkey". In order for this to work properly however you need to be in the same folder as the setup.py file lies in wich is usually directly in the getkey folder.

**Comment by Anonymous-Humanoid** [comment]
The solution provided by @greger555 is a lifesaver, just one correction:
> `def read_description(): with open('README.rst') as fd: return fd.read(encoding="utf-8")`

`def read_description(): with open('README.rst', encoding="utf-8") as fd: return fd.read()`

I also found that updating line 38 of platforms.py was necessary in favor of resolving "TypeError: can only concatenate str (not "bytes") to str":

> `buffer = ''`

`buffer = b''`
