### ISSUE TITLE
Bug while installing

### ISSUE THREAD

**Issue by Misticc-Dev** [kcsaff/getkey#24]
Whenever i use pip install getkey i get this error: 
```
Collecting getkey
  Using cached getkey-0.6.5.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "C:\Users\jusse\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\jusse\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jusse\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jusse\AppData\Local\Temp\pip-build-env-nef3dnt8\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jusse\AppData\Local\Temp\pip-build-env-nef3dnt8\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\jusse\AppData\Local\Temp\pip-build-env-nef3dnt8\overlay\Lib\site-packages\setuptools\build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jusse\AppData\Local\Temp\pip-build-env-nef3dnt8\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 37, in <module>
        File "<string>", line 11, in read_description
        File "C:\Users\jusse\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 876: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by Sidneys1** [comment]
Same issue, when `pip install`ing on Windows. Tried all available versions (0.6, 0.6.2, 0.6.3, 0.6.4, 0.6.5).

**Comment by Misticc-Dev** [comment]
I found the answer, just use pip install get-key

**Comment by Sidneys1** [comment]
> I found the answer, just use pip install get-key

Not a proper solution per se, but as this repo seems entirely abandoned by the author it's the best we'll get!

So I'd second this solution, the fork that provides `get-key` (https://github.com/TheIceBergBot/getkey) provides a drop-in replacement only differing in the pip package spelling.

**Comment by CFLKZ** [comment]
> I found the answer, just use pip install get-key

Thanks for the info, this helped me after trying to find a solution for 3.5 hours. MVP!
